# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(743, 843))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 641, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.ModelPage = QtWidgets.QWidget()
        self.ModelPage.setObjectName("ModelPage")
        self.DataFileGroup = QtWidgets.QGroupBox(self.ModelPage)
        self.DataFileGroup.setGeometry(QtCore.QRect(10, 50, 491, 61))
        self.DataFileGroup.setObjectName("DataFileGroup")
        self.DataFileEdit = QtWidgets.QTextEdit(self.DataFileGroup)
        self.DataFileEdit.setGeometry(QtCore.QRect(10, 20, 440, 31))
        self.DataFileEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DataFileEdit.setObjectName("DataFileEdit")
        self.toolButton = QtWidgets.QToolButton(self.DataFileGroup)
        self.toolButton.setGeometry(QtCore.QRect(450, 20, 31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/icon_library/softicons/16x16-free-application-icons-by-aha-soft/ico/Find.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setObjectName("toolButton")
        self.OutputDirGrp = QtWidgets.QGroupBox(self.ModelPage)
        self.OutputDirGrp.setGeometry(QtCore.QRect(10, 120, 491, 61))
        self.OutputDirGrp.setObjectName("OutputDirGrp")
        self.toolButton_2 = QtWidgets.QToolButton(self.OutputDirGrp)
        self.toolButton_2.setGeometry(QtCore.QRect(450, 20, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/icon_library/softicons/16x16-free-application-icons-by-aha-soft/ico/Downloads folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.OutputDirGrp)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 440, 31))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.ModelPage, "")
        self.ModelToolsPage = QtWidgets.QWidget()
        self.ModelToolsPage.setObjectName("ModelToolsPage")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.ModelToolsPage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 39, 2, 2))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DBFrame = QtWidgets.QFrame(self.ModelToolsPage)
        self.DBFrame.setGeometry(QtCore.QRect(10, 40, 611, 261))
        self.DBFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DBFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DBFrame.setObjectName("DBFrame")
        self.DBConnectionTextEdit = QtWidgets.QPlainTextEdit(self.DBFrame)
        self.DBConnectionTextEdit.setGeometry(QtCore.QRect(10, 30, 391, 29))
        self.DBConnectionTextEdit.setObjectName("DBConnectionTextEdit")
        self.DBConnLbl = QtWidgets.QLabel(self.DBFrame)
        self.DBConnLbl.setGeometry(QtCore.QRect(10, 10, 92, 17))
        self.DBConnLbl.setObjectName("DBConnLbl")
        self.FindDBConnectionBtn = QtWidgets.QToolButton(self.DBFrame)
        self.FindDBConnectionBtn.setGeometry(QtCore.QRect(400, 30, 29, 29))
        self.FindDBConnectionBtn.setIcon(icon)
        self.FindDBConnectionBtn.setObjectName("FindDBConnectionBtn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.DBFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 30, 151, 76))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CollateLineupsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.CollateLineupsBtn.setObjectName("CollateLineupsBtn")
        self.verticalLayout_2.addWidget(self.CollateLineupsBtn)
        self.RewriteSnapshotsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.RewriteSnapshotsBtn.setObjectName("RewriteSnapshotsBtn")
        self.verticalLayout_2.addWidget(self.RewriteSnapshotsBtn)
        self.tabWidget.addTab(self.ModelToolsPage, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut_2 = QtWidgets.QAction(MainWindow)
        self.actionCut_2.setObjectName("actionCut_2")
        self.actionCopy_2 = QtWidgets.QAction(MainWindow)
        self.actionCopy_2.setObjectName("actionCopy_2")
        self.actionPaste_2 = QtWidgets.QAction(MainWindow)
        self.actionPaste_2.setObjectName("actionPaste_2")
        self.actionVacuum = QtWidgets.QAction(MainWindow)
        self.actionVacuum.setObjectName("actionVacuum")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuEdit.addAction(self.actionCut_2)
        self.menuEdit.addAction(self.actionCopy_2)
        self.menuEdit.addAction(self.actionPaste_2)
        self.menuEdit.addSeparator()
        self.menuDatabase.addAction(self.actionVacuum)
        self.menuHelp.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.DBConnLbl.setBuddy(self.DBConnectionTextEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QT NRL Modelling Tools"))
        self.DataFileGroup.setTitle(_translate("MainWindow", "Data File"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.OutputDirGrp.setTitle(_translate("MainWindow", "Output Directory"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ModelPage), _translate("MainWindow", "Model"))
        self.DBConnectionTextEdit.setPlainText(_translate("MainWindow", "D:\\NRL_FILES\\SQLite\\ALEX_NRL_XML.sqlite"))
        self.DBConnectionTextEdit.setPlaceholderText(_translate("MainWindow", "D:\\\\NRL_FILES\\\\SQLite\\\\ALEX_NRL_XML.sqlite"))
        self.DBConnLbl.setText(_translate("MainWindow", "DB Connection"))
        self.FindDBConnectionBtn.setText(_translate("MainWindow", "..."))
        self.CollateLineupsBtn.setText(_translate("MainWindow", "Collate Lineups"))
        self.RewriteSnapshotsBtn.setText(_translate("MainWindow", "Rewrite Snapshots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ModelToolsPage), _translate("MainWindow", "Tools"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCut_2.setText(_translate("MainWindow", "Cut"))
        self.actionCopy_2.setText(_translate("MainWindow", "Copy"))
        self.actionPaste_2.setText(_translate("MainWindow", "Paste"))
        self.actionVacuum.setText(_translate("MainWindow", "Vacuum"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
