# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 843)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 1011, 731))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.DataFileGroup = QtWidgets.QGroupBox(self.widget)
        self.DataFileGroup.setGeometry(QtCore.QRect(10, 50, 491, 61))
        self.DataFileGroup.setObjectName("DataFileGroup")
        self.DataFileEdit = QtWidgets.QTextEdit(self.DataFileGroup)
        self.DataFileEdit.setGeometry(QtCore.QRect(10, 20, 440, 31))
        self.DataFileEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.DataFileEdit.setObjectName("DataFileEdit")
        self.toolButton = QtWidgets.QToolButton(self.DataFileGroup)
        self.toolButton.setGeometry(QtCore.QRect(450, 20, 31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/icon_library/softicons/16x16-free-application-icons-by-aha-soft/ico/Find.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(24, 24))
        self.toolButton.setObjectName("toolButton")
        self.OutputDirGrp = QtWidgets.QGroupBox(self.widget)
        self.OutputDirGrp.setGeometry(QtCore.QRect(510, 50, 491, 61))
        self.OutputDirGrp.setObjectName("OutputDirGrp")
        self.textEdit = QtWidgets.QTextEdit(self.OutputDirGrp)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 440, 31))
        self.textEdit.setObjectName("textEdit")
        self.toolButton_2 = QtWidgets.QToolButton(self.OutputDirGrp)
        self.toolButton_2.setGeometry(QtCore.QRect(450, 20, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/icon_library/softicons/16x16-free-application-icons-by-aha-soft/ico/Downloads folder.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setObjectName("toolButton_2")
        self.tabWidget.addTab(self.widget, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.DBConnectionGrp = QtWidgets.QGroupBox(self.widget1)
        self.DBConnectionGrp.setGeometry(QtCore.QRect(12, 60, 480, 80))
        self.DBConnectionGrp.setFlat(True)
        self.DBConnectionGrp.setObjectName("DBConnectionGrp")
        self.FindDBConnectionBtn = QtWidgets.QToolButton(self.DBConnectionGrp)
        self.FindDBConnectionBtn.setGeometry(QtCore.QRect(440, 20, 31, 31))
        self.FindDBConnectionBtn.setIcon(icon)
        self.FindDBConnectionBtn.setObjectName("FindDBConnectionBtn")
        self.textEdit_2 = QtWidgets.QTextEdit(self.DBConnectionGrp)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 20, 430, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.widget1, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.DataFileGroup.setTitle(_translate("MainWindow", "Data File"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.OutputDirGrp.setTitle(_translate("MainWindow", "Output Directory"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Model"))
        self.DBConnectionGrp.setTitle(_translate("MainWindow", "DB Connection "))
        self.FindDBConnectionBtn.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget1), _translate("MainWindow", "Setup"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
